name: Build Wine-tkg & Proton-tkg

on:
  schedule:
    - cron: '45 8,20 * * *'
  workflow_dispatch:

jobs:
  build-wine:
    name: Build Wine-tkg (Arch Container)
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - uses: actions/checkout@v4
      - name: Compile
        env:
          XDG_CACHE_HOME: /tmp/.cache
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu --noconfirm base-devel sudo
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown user -R . && cd wine-tkg-git

          # Apply your valve-exp-bleeding Wayland flag fix here
          sed -i 's/_GE_WAYLAND="false"/_GE_WAYLAND="true"/g' wine-tkg-profiles/wine-tkg-valve-exp-bleeding.cfg

          su user -c "yes|PKGDEST=/tmp/wine-tkg makepkg --noconfirm -s"

      - name: Archive Wine Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wine-tkg-build
          path: /tmp/wine-tkg

  build-proton:
    name: Build Proton-tkg (Sniper/Ubuntu Container)
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space
        uses: LizardByte/actions/actions/more_space@master
        with:
          analyze-space-savings: true
          clean-all: true
          safe-packages: "patch,git"
      - uses: actions/checkout@v4
      - name: Compile
        run: |
          cd proton-tkg
          sed -i 's/uninstaller="false"/uninstaller="true"/' proton-tkg.cfg
          sed -i 's/autoinstall="false"/autoinstall="true"/' proton-tkg.cfg
          sed -i 's/_no_container="true"/_no_container="false"/' proton-tkg.sh
          echo '_ci_build="true"' >> proton-tkg.cfg
          touch tarplz
          yes|./proton-tkg.sh
      - name: Archive Proton Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: proton-tkg-build
          path: proton-tkg/built/*.tar